const tabs=document.querySelectorAll('.source');
const form=document.querySelector('#downloadForm'),url=document.querySelector('#url'),quality=document.querySelector('#quality'),format=document.querySelector('#format');
const urlArea=document.querySelector('#urlArea'),uploadArea=document.querySelector('#uploadArea'),fileInput=document.querySelector('#fileInput');
const chooseBtn=document.querySelector('#chooseBtn'),fileName=document.querySelector('#fileName'),status=document.querySelector('#status'),btnText=document.querySelector('#btnText'),btn=form.querySelector('.main-btn');
const typeHint=document.querySelector('#typeHint'),uploadTitle=document.querySelector('#uploadTitle'),uploadSub=document.querySelector('#uploadSub'),pasteBtn=document.querySelector('#pasteBtn');
const progressWrap=document.querySelector('#progressWrap'),progressBar=document.querySelector('#progressBar'),progressPercent=document.querySelector('#progressPercent'),progressText=document.querySelector('#progressText');
let type='youtube',selectedFile=null;
function show(msg,error=false){status.textContent=msg;status.className='status '+(error?'error':'ok');status.classList.remove('hidden')}
function setFile(file){if(!file)return;const photo=type==='photo';if(photo&&!file.type.startsWith('image/'))return show('Pilih file foto yang valid.',true);if(!photo&&!file.type.startsWith('video/'))return show('Pilih file video yang valid.',true);selectedFile=file;fileName.textContent=`${file.name} • ${(file.size/1024/1024).toFixed(1)} MB`;fileName.classList.remove('hidden')}
function updateOptions(){if(type==='video'){quality.innerHTML='<option value="best">Original / Best Available</option><option value="2160">4K • 2160p</option><option value="1440">2K • 1440p</option><option value="1080">Full HD • 1080p</option><option value="720">HD • 720p</option><option value="480">SD • 480p</option>';format.innerHTML='<option value="mp4">MP4 Video</option><option value="webm">WebM Video</option>'}else if(type==='photo'){quality.innerHTML='<option value="1x">Enhance HD</option><option value="2x">AI Super Resolution 2×</option><option value="4x">AI Super Resolution 4×</option>';format.innerHTML='<option value="jpg">JPG High Quality</option><option value="png">PNG</option><option value="webp">WEBP</option>'}else{quality.innerHTML='<option value="best">Best Available</option><option value="2160">4K • 2160p</option><option value="1440">2K • 1440p</option><option value="1080">Full HD • 1080p</option><option value="720">HD • 720p</option><option value="480">SD • 480p</option>';format.innerHTML='<option value="mp4">MP4 Video</option><option value="webm">WebM Video</option><option value="mp3">MP3 Audio</option>'}}
tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');type=t.dataset.type;selectedFile=null;fileInput.value='';fileName.classList.add('hidden');const upload=type==='video'||type==='photo';urlArea.classList.toggle('hidden',upload);uploadArea.classList.toggle('hidden',!upload);document.querySelector('.settings').classList.remove('hidden');typeHint.textContent=type==='youtube'?'YouTube URL':type==='tiktok'?'TikTok URL':'UPLOAD DARI HP';if(type==='video'){uploadTitle.textContent='Upload video';uploadSub.textContent='MP4, MOV, MKV, WebM, AVI • maksimal 500 MB';fileInput.accept='video/*'}else if(type==='photo'){uploadTitle.textContent='Upload foto';uploadSub.textContent='JPG, PNG, WEBP • AI super-resolution';fileInput.accept='image/*'}else{url.placeholder=type==='youtube'?'https://www.youtube.com/watch?v=...':'https://www.tiktok.com/@user/video/...'}updateOptions()});
chooseBtn.onclick=()=>fileInput.click();fileInput.onchange=()=>setFile(fileInput.files[0]);
['dragenter','dragover'].forEach(e=>uploadArea.addEventListener(e,ev=>{ev.preventDefault();uploadArea.classList.add('drag')}));['dragleave','drop'].forEach(e=>uploadArea.addEventListener(e,ev=>{ev.preventDefault();uploadArea.classList.remove('drag')}));uploadArea.addEventListener('drop',ev=>setFile(ev.dataTransfer.files[0]));
pasteBtn.onclick=async()=>{try{url.value=await navigator.clipboard.readText();url.focus()}catch{show('Clipboard tidak bisa diakses. Paste link secara manual.',true)}};
function setProgress(p,text){progressWrap.classList.remove('hidden');progressBar.style.width=p+'%';progressPercent.textContent=p+'%';progressText.textContent=text}function hideProgress(){setTimeout(()=>progressWrap.classList.add('hidden'),900)}
let aiUpscalers={};function getAIUpscaler(scale){if(aiUpscalers[scale])return aiUpscalers[scale];if(!window.tf||!window.Upscaler)throw new Error('Engine AI belum termuat. Periksa koneksi internet lalu refresh.');const model=scale===2?window.ESRGANSlim2x:window.ESRGANSlim4x;if(!model)throw new Error(`Model ESRGAN ${scale}x tidak tersedia. Refresh halaman.`);return aiUpscalers[scale]=new window.Upscaler({model})}
async function fileToImage(file,maxDim=2048){const src=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Foto tidak bisa dibaca.'));i.src=src});if(Math.max(img.naturalWidth,img.naturalHeight)<=maxDim)return img;const ratio=maxDim/Math.max(img.naturalWidth,img.naturalHeight),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*ratio));c.height=Math.max(1,Math.round(img.naturalHeight*ratio));c.getContext('2d').drawImage(img,0,0,c.width,c.height);return await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=c.toDataURL('image/jpeg',.98)})}finally{URL.revokeObjectURL(src)}}
async function photoDownload(file){setProgress(8,'Menyiapkan foto...');const img=await fileToImage(file);let resultSrc;if(quality.value==='1x'){const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d');ctx.filter='contrast(1.05) saturate(1.03)';ctx.drawImage(img,0,0);resultSrc=c.toDataURL('image/jpeg',.98);setProgress(85,'Meningkatkan ketajaman...')}else{const upscaler=getAIUpscaler(Number(quality.value));setProgress(18,'Memuat model AI HD...');resultSrc=await upscaler.upscale(img,{patchSize:64,padding:4,awaitNextFrame:true,progress:p=>setProgress(Math.max(20,Math.round(20+p*70)),`AI memproses ${Math.round(p*100)}%`)})}const out=new Image();await new Promise((resolve,reject)=>{out.onload=resolve;out.onerror=()=>reject(new Error('Gagal membuat hasil foto.'));out.src=resultSrc});const c=document.createElement('canvas');c.width=out.naturalWidth;c.height=out.naturalHeight;c.getContext('2d').drawImage(out,0,0);const ext=format.value,mime={jpg:'image/jpeg',png:'image/png',webp:'image/webp'}[ext]||'image/jpeg';const blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Export foto gagal.')),mime,.98));const a=document.createElement('a'),obj=URL.createObjectURL(blob);a.href=obj;a.download=`VINN503_HD_${Date.now()}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(obj),5000);setProgress(100,`Foto HD selesai • ${c.width}×${c.height}`);show('Foto HD selesai. Download dimulai.');recordActivity('Berhasil','HD Foto · '+format.value);hideProgress()}
async function readResponse(r){let d;try{d=await r.json()}catch{throw new Error(`Server memberi respons tidak valid (HTTP ${r.status}).`)}if(!r.ok)throw new Error(d.error||`Permintaan gagal (HTTP ${r.status}).`);return d}
// AM Premium: promo link satu kali, entitlement dicatat server per ID perangkat.
const USER_KEY='vinn503_device_id_v1';
function deviceId(){try{let id=localStorage.getItem(USER_KEY);if(!/^[a-f0-9]{32}$/.test(id||'')){id=Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');localStorage.setItem(USER_KEY,id)}return id}catch{return ''}}
async function refreshPremium(){const msg=document.querySelector('#premiumMessage'),badge=document.querySelector('#premiumBadge');if(!msg||!badge)return;const id=deviceId();if(!id){msg.textContent='Penyimpanan browser tidak tersedia. Aktifkan local storage untuk memakai Premium.';return}try{const r=await fetch('/api/premium/status?userId='+encodeURIComponent(id),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Status Premium tidak bisa dimuat.');badge.textContent=d.premium?'AM PREMIUM':'FREE';badge.classList.toggle('active',d.premium);msg.textContent=d.premium?'AM Premium aktif sampai '+new Date(d.expiresAt).toLocaleDateString('id-ID')+'.':'Belum ada AM Premium aktif di perangkat ini.'}catch{msg.textContent='Status Premium belum bisa diperiksa. Coba muat ulang halaman.'}}
const premiumToast=document.querySelector('#siteToast');
const showPremiumNotice=()=>{
  if(!premiumToast)return;
  premiumToast.classList.add('is-visible');
  premiumToast.setAttribute('aria-hidden','false');
  clearTimeout(window.__premiumToastTimer);
  window.__premiumToastTimer=setTimeout(()=>{
    premiumToast.classList.remove('is-visible');
    premiumToast.setAttribute('aria-hidden','true');
  },5200);
};
document.querySelector('#claimPremium')?.addEventListener('click',()=>{
  showPremiumNotice();
});
premiumToast?.querySelector('.site-toast-close')?.addEventListener('click',()=>{
  premiumToast.classList.remove('is-visible');
  premiumToast.setAttribute('aria-hidden','true');
  clearTimeout(window.__premiumToastTimer);
});
refreshPremium();
const HISTORY_KEY='vinn503_history_v1';
function readHistory(){try{const x=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function saveHistory(item){const rows=[item,...readHistory()].slice(0,20);try{localStorage.setItem(HISTORY_KEY,JSON.stringify(rows))}catch{}renderHistory()}
function renderHistory(){const list=document.querySelector('#downloadHistory');if(!list)return;const rows=readHistory();list.replaceChildren();if(!rows.length){const li=document.createElement('li');li.className='history-empty';li.textContent='Belum ada aktivitas.';list.append(li);return}rows.forEach(row=>{const li=document.createElement('li');li.className='history-item';const title=document.createElement('strong');title.textContent=row.title;const meta=document.createElement('span');meta.textContent=new Date(row.time).toLocaleString()+' · '+row.result;li.append(title,meta);list.append(li)})}
function recordActivity(result,detail){saveHistory({title:String(detail||'Aktivitas media').slice(0,100),result,time:new Date().toISOString()})}
async function checkSystem(){const pill=document.querySelector('#systemStatus'),message=document.querySelector('#systemMessage');if(!pill||!message)return;pill.className='system-pill checking';pill.textContent='Memeriksa…';message.textContent='Memeriksa server, yt-dlp, FFmpeg, dan konfigurasi AI.';try{const r=await fetch('/api/health',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json(),c=d.checks||{};const item=(label,ok)=>`${label}: ${ok?'Terdeteksi':'Tidak tersedia'}`;message.textContent=[item('Server Node.js',c.node),item('yt-dlp',c.ytDlp),item('FFmpeg',c.ffmpeg),`Gemini API key: ${c.geminiConfigured?'Terkonfigurasi':'Belum diatur'}`,`Model AI: ${c.geminiModel||'tidak diketahui'}`].join(' · ');const healthy=!!(c.node&&c.ytDlp&&c.ffmpeg);pill.className='system-pill '+(healthy?'online':'offline');pill.textContent=healthy?'Server online':'Ada tool belum siap';if(!c.geminiConfigured)message.textContent+=' · VINN AI belum aktif sampai GEMINI_API_KEY diatur.'}catch{pill.className='system-pill offline';pill.textContent='Tidak terhubung';message.textContent='Server tidak dapat dijangkau. Pastikan server berjalan dan coba lagi.'}}
document.querySelector('#refreshStatus')?.addEventListener('click',checkSystem);
document.querySelector('#clearHistory')?.addEventListener('click',()=>{try{localStorage.removeItem(HISTORY_KEY)}catch{}renderHistory()});
function showReportToast(title,message){let toast=document.querySelector('#reportToast');if(!toast){toast=document.createElement('div');toast.id='reportToast';toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');toast.style.cssText='position:fixed;z-index:99999;right:18px;bottom:18px;max-width:min(390px,calc(100vw - 36px));padding:17px 18px;border:1px solid rgba(97,230,176,.45);border-radius:16px;background:linear-gradient(135deg,#102b28,#141a27);color:#f5fff9;box-shadow:0 18px 55px #0008;font:14px/1.45 system-ui;opacity:0;transform:translateY(12px);transition:opacity .25s,transform .25s';document.body.append(toast)}toast.replaceChildren();const mark=document.createElement('div');mark.textContent='✓  '+title;mark.style.cssText='font-weight:800;color:#75edb7;font-size:15px;margin-bottom:5px';const copy=document.createElement('div');copy.textContent=message;copy.style.color='#c7d9d2';toast.append(mark,copy);requestAnimationFrame(()=>{toast.style.opacity='1';toast.style.transform='translateY(0)'});clearTimeout(window.__reportToastTimer);window.__reportToastTimer=setTimeout(()=>{toast.style.opacity='0';toast.style.transform='translateY(12px)'},6000)}
document.querySelector('#sendBugReport')?.addEventListener('click',async()=>{const box=document.querySelector('#bugDescription'),feedback=document.querySelector('#bugFeedback'),detail=box.value.trim();if(!detail){feedback.textContent='Tuliskan kendala terlebih dahulu.';return}const button=document.querySelector('#sendBugReport');button.disabled=true;feedback.textContent='Mengirim laporan ke dashboard admin...';try{const r=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description:detail,category:'Laporan pengguna',page:location.pathname,userAgent:navigator.userAgent})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Laporan gagal disimpan.');feedback.textContent='Laporan anda terkirim. Terima kasih atas laporan-nya! ID: '+d.id;feedback.classList.add('success');box.value='';showReportToast('Laporan anda terkirim!','Terima kasih atas laporan-nya. Tim VINN503 akan meninjaunya. ID: '+d.id)}catch(e){feedback.textContent='Gagal mengirim laporan: '+e.message+' Pastikan server berjalan.';feedback.classList.remove('success')}finally{button.disabled=false}});
renderHistory();checkSystem();
form.onsubmit=async e=>{e.preventDefault();btn.disabled=true;btnText.textContent='MEMPROSES...';try{if(type==='photo'){if(!selectedFile)throw new Error('Pilih foto dulu.');await photoDownload(selectedFile);return}if(type==='video'){if(!selectedFile)throw new Error('Pilih video dulu.');if(selectedFile.size>100*1024*1024)throw new Error('Ukuran video maksimal 100 MB.');show('Mengunggah video ke server...');setProgress(10,'Mengunggah video...');const fd=new FormData();fd.append('video',selectedFile);fd.append('quality',quality.value);fd.append('format',format.value);const data=await readResponse(await fetch('/api/process-video',{method:'POST',body:fd}));setProgress(100,'Video siap');const a=document.createElement('a');a.href=data.downloadUrl;a.download='';document.body.appendChild(a);a.click();a.remove();show('Video selesai diproses. Download dimulai.');recordActivity('Berhasil','HD Video · '+format.value);hideProgress();return}const value=url.value.trim();if(!value)throw new Error('Masukkan URL YouTube atau TikTok.');let parsed;try{parsed=new URL(value)}catch{throw new Error('Format URL tidak valid.')}if(!['http:','https:'].includes(parsed.protocol))throw new Error('URL harus menggunakan HTTP atau HTTPS.');show('Menghubungi downloader. Link privat atau media yang dibatasi mungkin tidak bisa diakses.');setProgress(15,'Memeriksa link media...');const data=await readResponse(await fetch('/api/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:value,type,quality:quality.value,format:format.value})}));setProgress(100,'File siap diunduh');const a=document.createElement('a');a.href=data.downloadUrl;a.download='';document.body.appendChild(a);a.click();a.remove();show('File siap. Download dimulai.');recordActivity('Berhasil',type+' · '+format.value+' · '+quality.value);hideProgress()}catch(err){show(err.message||'Terjadi kesalahan.',true);recordActivity('Gagal',type+' · '+(err.message||'Terjadi kesalahan.'));hideProgress()}finally{btn.disabled=false;btnText.textContent='DOWNLOAD SEKARANG'}};
const loader=document.querySelector('#welcomeLoader');window.addEventListener('load',()=>setTimeout(()=>loader?.classList.add('done'),700));setTimeout(()=>loader?.classList.add('done'),3500);
const welcomeVideo=document.querySelector('#welcomeVideo');if(welcomeVideo){welcomeVideo.addEventListener('contextmenu',e=>e.preventDefault());welcomeVideo.addEventListener('click',e=>e.preventDefault());welcomeVideo.addEventListener('keydown',e=>e.preventDefault());welcomeVideo.addEventListener('error',()=>{const frame=welcomeVideo.closest('.video-frame');if(frame)frame.classList.add('video-unavailable')})}
